worker_processes 1;

events {
    worker_connections 512;
}

stream {
    map $ssl_preread_server_name $hybrid_tcp_backend {
        <YOUR_DOMAIN> xray_backend;
        default decoy_backend;
    }

    upstream xray_backend {
        server xray:8444;
    }

    upstream decoy_backend {
        server nginx:8443;
    }

    upstream hysteria_udp {
        server hysteria:8445;
    }

    server {
        listen 443;
        proxy_pass $hybrid_tcp_backend;
        ssl_preread on;
    }

    server {
        listen 443 udp reuseport;
        listen [::]:443 udp reuseport;
        proxy_pass hysteria_udp;
        proxy_timeout 20s;
    }
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile    on;
    keepalive_timeout 65;
    access_log off;

    server {
        listen 8443 ssl;
        http2 on;
        server_name _;

        ssl_certificate     /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;
        ssl_protocols TLSv1.3 TLSv1.2;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
